version: '3.9'

services:
  db:
    # container_name: interactive-comments-test
    ports:
      - 5433:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: test
    # command: tail -F anything

volumes:
  database-data:
